version: '3.9'
services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: it_planeta_postgres
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=it_planeta
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: it_planeta_api
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: all
  # all - запуск всех тестов из трёх доступных этапов
  # 0, 1 или 2 - запуск тестов для соответствующего этапа