// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	Password  string
	Deleted   bool
}

type Animal struct {
	ID               int64
	ChippingLocation int64
	Weight           float64
	Length           float64
	Height           float64
	Gender           string
	LifeStatus       string
	ChippingDate     time.Time
	Chipper          int64
	DeathDate        sql.NullTime
	Deleted          bool
}

type AnimalGender struct {
	Value string
}

type AnimalLifeStatus struct {
	Value string
}

type AnimalToType struct {
	ID     int64
	Animal int64
	Type   int64
}

type AnimalType struct {
	ID      int64
	Value   string
	Deleted bool
}

type AnimalVisitedLocation struct {
	ID       int64
	Location int64
	Animal   int64
	Date     time.Time
	Deleted  bool
}

type LocationPoint struct {
	ID        int64
	Latitude  float64
	Longitude float64
	Deleted   bool
}
