// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package queries

import ()

type Account struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Password  string
}
